/**
 * Static default content for the Terms of Service page.
 * Used when no API/CMS data is provided. Prepared for future data binding.
 */

import type { TosContent } from '@/types/terms-of-service'

export const DEFAULT_TOS_CONTENT: TosContent = {
  version: '1.0',
  lastUpdated: '2025-03-06',
  sections: [
    {
      id: 'acceptance',
      heading: 'Acceptance of Terms',
      body:
        'By accessing or using Gbox360 ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the Platform. These Terms constitute a legally binding agreement between you and Gbox360.',
      isImportant: true,
    },
    {
      id: 'definitions',
      heading: 'Definitions',
      body:
        'For the purposes of these Terms, the following definitions apply:',
      subsections: [
        {
          heading: 'Platform',
          text:
            'Gbox360, including its website, applications, APIs, and all related services that provide the Investor Perception Index (IPI) and narrative intelligence features.',
        },
        {
          heading: 'User',
          text:
            'Any individual or entity that accesses or uses the Platform, including authenticated users, administrators, and auditors.',
        },
        {
          heading: 'Content',
          text:
            'All data, text, visualizations, audit artifacts, and materials generated or displayed through the Platform.',
        },
      ],
    },
    {
      id: 'account-responsibilities',
      heading: 'Account and User Responsibilities',
      body:
        'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to:',
      listItems: [
        'Provide accurate and complete registration information',
        'Notify us immediately of any unauthorized access or security breach',
        'Use the Platform only for lawful purposes and in accordance with these Terms',
        'Not share your account credentials with third parties',
      ],
    },
    {
      id: 'acceptable-use',
      heading: 'Acceptable Use',
      body:
        'You may not misuse the Platform. Prohibited activities include, but are not limited to:',
      listItems: [
        'Attempting to gain unauthorized access to the Platform, other accounts, or systems',
        'Using the Platform for any illegal purpose or in violation of applicable laws',
        'Interfering with or disrupting the integrity or performance of the Platform',
        'Redistributing, reselling, or sublicensing Platform content without prior written consent',
        'Reverse engineering, decompiling, or disassembling any part of the Platform',
        'Using automated means (bots, scrapers) to access the Platform without authorization',
      ],
      isImportant: true,
    },
    {
      id: 'data-ownership',
      heading: 'Data Ownership and License',
      body:
        'You retain ownership of any data you submit to the Platform. By submitting data, you grant Gbox360 a limited, non-exclusive license to process, store, and display such data solely for the purpose of providing the Platform services. Gbox360 does not claim ownership of your data. Export and audit artifacts generated by the Platform are for your internal use and compliance purposes; redistribution may be subject to separate agreements.',
    },
    {
      id: 'export-terms',
      heading: 'Export and Audit Artifacts',
      body:
        'The Platform enables generation of signed audit artifacts (JSON and PDF) that include raw payload references, calculation inputs, weights, and integrity hashes. These artifacts are intended for compliance, audit, and internal decision support. You acknowledge that:',
      subsections: [
        {
          heading: 'Use of Exports',
          text:
            'Exported artifacts are provided for your lawful use. You are responsible for ensuring that your use of exported data complies with applicable regulations and third-party terms.',
        },
        {
          heading: 'Integrity',
          text:
            'Artifacts are signed using KMS and include content hashes (SHA256) for verification. Tampering with signed artifacts may invalidate their integrity.',
        },
      ],
    },
    {
      id: 'disclaimers',
      heading: 'Disclaimers',
      body:
        'THE PLATFORM AND ALL CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. GBOX360 DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THE INVESTOR PERCEPTION INDEX (IPI) AND NARRATIVE INTELLIGENCE FEATURES ARE FOR INFORMATIONAL AND DECISION-SUPPORT PURPOSES ONLY. THEY DO NOT CONSTITUTE INVESTMENT, LEGAL, OR TAX ADVICE. YOU SHOULD CONDUCT YOUR OWN DUE DILIGENCE AND CONSULT QUALIFIED PROFESSIONALS BEFORE MAKING ANY DECISIONS.',
      isDisclaimer: true,
    },
    {
      id: 'limitation-of-liability',
      heading: 'Limitation of Liability',
      body:
        'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, GBOX360 AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE PLATFORM. IN NO EVENT SHALL GBOX360\'S AGGREGATE LIABILITY EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO GBOX360 IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).',
      isDisclaimer: true,
    },
    {
      id: 'indemnification',
      heading: 'Indemnification',
      body:
        'You agree to indemnify, defend, and hold harmless Gbox360 and its affiliates from and against any claims, damages, losses, liabilities, and expenses (including reasonable attorneys\' fees) arising out of or related to your use of the Platform, your violation of these Terms, or your violation of any third-party rights.',
    },
    {
      id: 'termination',
      heading: 'Termination',
      body:
        'Gbox360 may suspend or terminate your access to the Platform at any time, with or without cause or notice. Upon termination, your right to use the Platform ceases immediately. Provisions that by their nature should survive termination (including disclaimers, limitation of liability, and indemnification) shall survive.',
    },
    {
      id: 'changes-to-terms',
      heading: 'Changes to These Terms',
      body:
        'We may update these Terms from time to time. Material changes will be communicated via email or a prominent notice on the Platform. The "Last updated" date at the top reflects the most recent revision. Your continued use of the Platform after changes constitutes acceptance of the updated Terms. If you do not agree to the updated Terms, you must stop using the Platform.',
    },
    {
      id: 'governing-law',
      heading: 'Governing Law and Disputes',
      body:
        'These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Gbox360 is incorporated, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved in the courts of that jurisdiction.',
    },
    {
      id: 'contact',
      heading: 'Contact',
      body:
        'For questions about these Terms, legal inquiries, or support, please contact us:',
      subsections: [
        {
          heading: 'Legal and Terms',
          text: 'Email: legal@gbox360.com',
        },
        {
          heading: 'Support',
          text: 'Email: support@gbox360.com',
        },
      ],
    },
  ],
  notes: [
    'These Terms are effective as of the Last updated date shown above.',
    'By using Gbox360, you acknowledge that you have read, understood, and agree to be bound by these Terms.',
  ],
}
